# Generated by Django 5.0.4 on 2024-05-04 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 4, 12, 9, 12, 68435, tzinfo=datetime.timezone.utc)),
        ),
    ]
