# Generated by Django 5.0.4 on 2024-05-25 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_question_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 25, 12, 50, 4, 485540, tzinfo=datetime.timezone.utc)),
        ),
    ]
